# Generated by Django 3.1.7 on 2021-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20210420_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='profile')),
                ('calendar', models.ManyToManyField(blank=True, to='students.Event')),
                ('courses', models.ManyToManyField(blank=True, to='courses.Course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
