# Generated by Django 3.2 on 2021-04-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210420_1815'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('email',)},
        ),
    ]
