# Generated by Django 3.2 on 2021-04-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210420_1230'),
        ('students', '0003_alter_student_unique_together'),
    ]

    operations = [
    ]
