# Generated by Django 3.2 on 2021-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='skills',
            field=models.CharField(default='C', max_length=1000),
        ),
    ]
