# Generated by Django 3.2 on 2021-04-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='skills',
            field=models.CharField(default='C', max_length=1000),
        ),
    ]
