# Generated by Django 3.2 on 2021-04-19 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '__first__'),
        ('groups', '0002_auto_20210416_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.student')),
            ],
        ),
    ]
