# Generated by Django 3.2 on 2021-04-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupMembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
