# Generated by Django 3.2 on 2021-04-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '__first__'),
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=120)),
                ('preferredmeetingLoc', models.CharField(max_length=500)),
                ('preferredmeetingStartTime', models.DateTimeField()),
                ('preferredmeetingEndTime', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='groupAvatar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
