# Generated by Django 3.2 on 2021-04-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseSkills', '0001_initial'),
        ('groups', '0003_groupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='groups.group')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courseSkills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='groups.group')),
            ],
        ),
    ]
