# Generated by Django 3.2 on 2021-04-20 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '__first__'),
        ('groups', '0004_calendar_groupskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='preferredmeetingEndTime',
        ),
        migrations.RemoveField(
            model_name='group',
            name='preferredmeetingStartTime',
        ),
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
