# Generated by Django 3.1.7 on 2021-04-20 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseSkills', '0002_auto_20210419_2359'),
        ('groups', '0005_auto_20210419_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookingForSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='groups.group')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courseSkills.skill')),
            ],
        ),
    ]
