# Generated by Django 3.2 on 2021-04-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20210420_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='eventName',
            field=models.CharField(default='Meeting', max_length=200),
        ),
    ]
