# Generated by Django 3.1.7 on 2021-04-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_calendar_group'),
        ('groups', '0006_lookingforskill'),
    ]

    operations = [
    ]
