# Generated by Django 3.2 on 2021-04-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('skill', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
