# Generated by Django 3.1.7 on 2021-04-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.CharField(blank=True, default=True, max_length=10000, null=True),
        ),
    ]
