# Generated by Django 3.2 on 2021-04-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210420_1230'),
        ('courses', '0003_auto_20210420_1919'),
    ]

    operations = [
    ]
